// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyA5z2MaEB785J978fJXnEhnMWAMBqIF8pU",
      authDomain: "eki-express-74357.firebaseapp.com",
      projectId: "eki-express-74357",
      storageBucket: "eki-express-74357.appspot.com",
      messagingSenderId: "586680111067",
      appId: "1:586680111067:web:614197c9e24a369f64e1fe",
      measurementId: "G-SC7Z2DNYSP");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzqqP2DD8NQnkhjkYV98VVwnE-5Nk1yes',
    appId: '1:586680111067:android:b1e52e7d1b01fbf364e1fe',
    messagingSenderId: '586680111067',
    projectId: 'eki-express-74357',
    storageBucket: "eki-express-74357.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzqqP2DD8NQnkhjkYV98VVwnE-5Nk1yes',
    appId: '1:586680111067:ios:453e1ffc734db45464e1fe',
    messagingSenderId: '586680111067',
    projectId: 'eki-express-74357',
    storageBucket: "eki-express-74357.appspot.com",
    iosClientId:
        '773582855575-tk8p7f91vgbapg3cb13i35k3m1cso4an.apps.googleusercontent.com',
    iosBundleId: 'com.apssmartbazaar.app',
  );
}
